# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cookie.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Cookie_Form(object):
    def setupUi(self, Cookie_Form):
        Cookie_Form.setObjectName("Cookie_Form")
        Cookie_Form.resize(938, 783)
        self.widget = QtWidgets.QWidget(Cookie_Form)
        self.widget.setGeometry(QtCore.QRect(100, 620, 641, 61))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.erp_btn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.erp_btn.sizePolicy().hasHeightForWidth())
        self.erp_btn.setSizePolicy(sizePolicy)
        self.erp_btn.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.erp_btn.setFont(font)
        self.erp_btn.setObjectName("erp_btn")
        self.horizontalLayout.addWidget(self.erp_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.wms_btn = QtWidgets.QPushButton(self.widget)
        self.wms_btn.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.wms_btn.setFont(font)
        self.wms_btn.setObjectName("wms_btn")
        self.horizontalLayout.addWidget(self.wms_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.clear_cookies = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_cookies.sizePolicy().hasHeightForWidth())
        self.clear_cookies.setSizePolicy(sizePolicy)
        self.clear_cookies.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clear_cookies.setFont(font)
        self.clear_cookies.setObjectName("clear_cookies")
        self.horizontalLayout.addWidget(self.clear_cookies)
        self.widget1 = QtWidgets.QWidget(Cookie_Form)
        self.widget1.setGeometry(QtCore.QRect(30, 150, 864, 481))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(60, 20))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.web_widget = QtWidgets.QWidget(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.web_widget.sizePolicy().hasHeightForWidth())
        self.web_widget.setSizePolicy(sizePolicy)
        self.web_widget.setMinimumSize(QtCore.QSize(800, 400))
        self.web_widget.setMaximumSize(QtCore.QSize(800, 400))
        self.web_widget.setObjectName("web_widget")
        self.verticalLayout.addWidget(self.web_widget)
        self.widget2 = QtWidgets.QWidget(Cookie_Form)
        self.widget2.setGeometry(QtCore.QRect(30, 10, 871, 141))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.log_text = QtWidgets.QTextBrowser(self.widget2)
        self.log_text.setObjectName("log_text")
        self.verticalLayout_2.addWidget(self.log_text)

        self.retranslateUi(Cookie_Form)
        QtCore.QMetaObject.connectSlotsByName(Cookie_Form)

    def retranslateUi(self, Cookie_Form):
        _translate = QtCore.QCoreApplication.translate
        Cookie_Form.setWindowTitle(_translate("Cookie_Form", "cookies 更新小工具"))
        self.erp_btn.setText(_translate("Cookie_Form", "ERP cookies"))
        self.wms_btn.setText(_translate("Cookie_Form", "WMS cookies"))
        self.clear_cookies.setText(_translate("Cookie_Form", "清理缓存"))
        self.label.setText(_translate("Cookie_Form", "浏览器："))
        self.label_2.setText(_translate("Cookie_Form", "日志："))

